---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  product_name: chef
  product_version: 14.2
  enforce_idempotency: true
  multiple_converge: 2
  solo_rb:
    treat_deprecation_warnings_as_errors: true
    silence_deprecation_warnings:
    - chef-25  #Depending on the windows cookbook fails this right now (Build Essential)

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: fedora-28
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
- name: repo
  run_list:
    - recipe[test::repository]
- name: server_install
  run_list:
    - recipe[test::server_install]
- name: client_install
  run_list:
    - recipe[test::client_install]
- name: access
  run_list:
    - recipe[test::access]
- name: ident
  run_list:
    - recipe[test::ident]
- name: extension
  run_list:
    - recipe[test::extension]
- name: initdb_locale
  run_list:
    - recipe[test::initdb_locale]
  includes: [centos-7]
