---
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown

version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2

workflows:
  kitchen:
    jobs:
      # Lint and Unit Test
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery

      - kitchen/dokken-single:
          name: repo
          suite: repo
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: server-install
          suite: server-install
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: client-install
          suite: client-install
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: access-centos-7
          suite: access-centos-7
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: ident-centos-7
          suite: ident-centos-7
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: extension-centos-7
          suite: extension-centos-7
          requires:
            *lint_and_unit
      - kitchen/dokken-single:
          name: initdb-locale-centos-7
          suite: initdb-locale-centos-7
          requires:
            *lint_and_unit
