version: 2
jobs:
  danger:
    docker:
       - image: circleci/ruby
    steps:
      - checkout
      - run:
          name: Install Danger
          command: gem install danger
      - run:
          name: Run Danger
          command: danger

  lint:
    machine: true
    environment:
      KITCHEN_LOCAL_YAML: .kitchen.dokken.yml
    steps:
      - checkout
      - run:
          name: Install Chef
          command: |
            wget https://packages.chef.io/files/stable/chefdk/2.4.17/ubuntu/16.04/chefdk_2.4.17-1_amd64.deb
            sudo dpkg -i ./chefdk_2.4.17-1_amd64.deb
            RUBY_ABI_VERSION=`ls /opt/chefdk/embedded/lib/ruby/gems/`
            export GEM_ROOT="/opt/chefdk/embedded/lib/ruby/gems/$RUBY_ABI_VERSION"
            export GEM_HOME="$EXPANDED_HOME/.chefdk/gem/ruby/$RUBY_ABI_VERSION"
            export GEM_PATH="$EXPANDED_HOME/.chefdk/gem/ruby/$RUBY_ABI_VERSION:/opt/chefdk/embedded/lib/ruby/gems/$RUBY_ABI_VERSION"
            echo 'export PATH="/opt/chefdk/embedded/bin:$PATH"' >> ~/.configuration_file && source ~/.configuration_file
      - run:
          name: Unit Test
          command: chef exec delivery local all
      - persist_to_workspace:
          root: /opt
          paths:
            - chefdk

    repo:
      machine: true
      environment:
        KITCHEN_LOCAL_YAML: .kitchen.dokken.yml
      steps:
        - checkout
        - attach_workspace:
            at: /opt
        - run:
            name: kitchen test repo
            command: |
              RUBY_ABI_VERSION=`ls /opt/chefdk/embedded/lib/ruby/gems/`
              export GEM_ROOT="/opt/chefdk/embedded/lib/ruby/gems/$RUBY_ABI_VERSION"
              export GEM_HOME="$EXPANDED_HOME/.chefdk/gem/ruby/$RUBY_ABI_VERSION"
              export GEM_PATH="$EXPANDED_HOME/.chefdk/gem/ruby/$RUBY_ABI_VERSION:/opt/chefdk/embedded/lib/ruby/gems/$RUBY_ABI_VERSION"
              echo 'export PATH="/opt/chefdk/embedded/bin:$PATH"' >> ~/.configuration_file && source ~/.configuration_file
              kitchen test repo

workflows:
  version: 2
  build:
    jobs:
      - danger:
          context: Danger
      - lint
