kitchen: &kitchen
  machine: true
  environment:
    KITCHEN_LOCAL_YAML: .kitchen.dokken.yml
  steps:
    - checkout
    - run:
        name: Install Chef
        command: |
          wget https://packages.chef.io/files/stable/chefdk/2.4.17/ubuntu/16.04/chefdk_2.4.17-1_amd64.deb
          sudo dpkg -i ./chefdk_2.4.17-1_amd64.deb
          RUBY_ABI_VERSION=`ls /opt/chefdk/embedded/lib/ruby/gems/`
          export GEM_ROOT="/opt/chefdk/embedded/lib/ruby/gems/$RUBY_ABI_VERSION"
          export GEM_HOME="$EXPANDED_HOME/.chefdk/gem/ruby/$RUBY_ABI_VERSION"
          export GEM_PATH="$EXPANDED_HOME/.chefdk/gem/ruby/$RUBY_ABI_VERSION:/opt/chefdk/embedded/lib/ruby/gems/$RUBY_ABI_VERSION"
          echo 'export PATH="/opt/chefdk/embedded/bin:$PATH"' >> ~/.configuration_file && source ~/.configuration_file
    - run:
        name: amazonlinux
        command: kitchen test $CIRCLE_JOB-amazonlinux
    - run:
        name: centos-6
        command: kitchen test $CIRCLE_JOB-centos-6
    - run:
        name: centos-7
        command: kitchen test $CIRCLE_JOB-centos-7
    - run:
        name: debian-8
        command: kitchen test $CIRCLE_JOB-debian-8
    - run:
        name: debian-9
        command: kitchen test $CIRCLE_JOB-debian-9
    - run:
        name: fedora-28
        command: kitchen test $CIRCLE_JOB-fedora-28
    - run:
        name: ubuntu-16.04
        command: kitchen test $CIRCLE_JOB-ubuntu-16.04
    - run:
        name: ubuntu-18.04
        command: kitchen test $CIRCLE_JOB-ubuntu-18.04

version: 2
jobs:
  danger:
    docker:
       - image: circleci/ruby
    steps:
      - checkout
      - run:
          name: Install Danger
          command: gem install danger
      - run:
          name: Run Danger
          command: danger

  lint:
    machine: true
    environment:
      KITCHEN_LOCAL_YAML: .kitchen.dokken.yml
    steps:
      - checkout
      - run:
          name: Install Chef
          command: |
            wget https://packages.chef.io/files/stable/chefdk/2.4.17/ubuntu/16.04/chefdk_2.4.17-1_amd64.deb
            sudo dpkg -i ./chefdk_2.4.17-1_amd64.deb
            RUBY_ABI_VERSION=`ls /opt/chefdk/embedded/lib/ruby/gems/`
            export GEM_ROOT="/opt/chefdk/embedded/lib/ruby/gems/$RUBY_ABI_VERSION"
            export GEM_HOME="$EXPANDED_HOME/.chefdk/gem/ruby/$RUBY_ABI_VERSION"
            export GEM_PATH="$EXPANDED_HOME/.chefdk/gem/ruby/$RUBY_ABI_VERSION:/opt/chefdk/embedded/lib/ruby/gems/$RUBY_ABI_VERSION"
            echo 'export PATH="/opt/chefdk/embedded/bin:$PATH"' >> ~/.configuration_file && source ~/.configuration_file
      - run:
          name: Unit Test
          command: chef exec delivery local all

  repo:
    <<: *kitchen
  server:
    <<: *kitchen
  client:
    <<: *kitchen
  access:
    <<: *kitchen
  ident:
    <<: *kitchen
  extension:
    <<: *kitchen
  initdb:
    machine: true
    environment:
      KITCHEN_LOCAL_YAML: .kitchen.dokken.yml
    steps:
      - checkout
      - run:
          name: Install Chef
          command: |
            wget https://packages.chef.io/files/stable/chefdk/2.4.17/ubuntu/16.04/chefdk_2.4.17-1_amd64.deb
            sudo dpkg -i ./chefdk_2.4.17-1_amd64.deb
            RUBY_ABI_VERSION=`ls /opt/chefdk/embedded/lib/ruby/gems/`
            export GEM_ROOT="/opt/chefdk/embedded/lib/ruby/gems/$RUBY_ABI_VERSION"
            export GEM_HOME="$EXPANDED_HOME/.chefdk/gem/ruby/$RUBY_ABI_VERSION"
            export GEM_PATH="$EXPANDED_HOME/.chefdk/gem/ruby/$RUBY_ABI_VERSION:/opt/chefdk/embedded/lib/ruby/gems/$RUBY_ABI_VERSION"
            echo 'export PATH="/opt/chefdk/embedded/bin:$PATH"' >> ~/.configuration_file && source ~/.configuration_file
      - run:
          command: kitchen test initdb-locale-centos-7

workflows:
  version: 2
  build:
    jobs:
      - danger:
          context: Danger
      - lint
      - repo:
          requires:
            - lint
            - danger
      - server:
          requires:
            - lint
            - danger
      - client:
          requires:
            - lint
            - danger
      - access:
          requires:
            - lint
            - danger
      - ident:
          requires:
            - lint
            - danger
      - extension:
          requires:
            - lint
            - danger
      - initdb:
          requires:
            - lint
            - danger
