# kitchen: &kitchen
#   machine: true
#   environment:
#     KITCHEN_LOCAL_YAML: .kitchen.dokken.yml
#   steps:
#     - checkout
#     - run:
#         name: Install Chef
#         <<: *install_chef
    # - run:
    #     name: amazonlinux
    #     command: kitchen test $CIRCLE_JOB-amazonlinux
    # Network failure to be fixed
    # - run:
    #     name: centos-6
    #     command: kitchen test $CIRCLE_JOB-centos-6
    # - run:
    #     name: centos-7
    #     command: kitchen test $CIRCLE_JOB-centos-7
    # - run:
    #     name: debian-8
    #     command: kitchen test $CIRCLE_JOB-debian-8
    # - run:
    #     name: debian-9
    #     command: kitchen test $CIRCLE_JOB-debian-9
    # - run:
    #     name: fedora-28
    #     command: kitchen test $CIRCLE_JOB-fedora-28
    # - run:
    #     name: ubuntu-16.04
    #     command: kitchen test $CIRCLE_JOB-ubuntu-1604
    # - run:
    #    name: ubuntu-18.04
    #    command: kitchen test $CIRCLE_JOB-ubuntu-1804
     # service[postgresql] action startToo long with no output (exceeded 10m0s)

  # repo:
  #   <<: *kitchen
  # server-install:
  #   <<: *kitchen
  # client-install:
  #   <<: *kitchen
  # access:
  #   <<: *kitchen
  # ident:
  #   <<: *kitchen
  # extension:
  #   <<: *kitchen
  # initdb:
  #   machine: true
  #   environment:
  #     KITCHEN_LOCAL_YAML: .kitchen.dokken.yml
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install Chef
  #         <<: *install_chef
  #     - run:
  #         command: kitchen test initdb-locale-centos-7

version: 2.1
workflows:
  build:
    jobs:
      - sous-chefs/danger:
          context: Danger
          name: Danger
      - sous-chefs/lint:
          name: Lint
      # - repo:
      #     requires:
      #       - lint
      #       - danger
      # - server-install:
      #     requires:
      #       - lint
      #       - danger
      # - client-install:
      #     requires:
      #       - lint
      #       - danger
      # - access:
      #     requires:
      #       - lint
      #       - danger
      # - ident:
      #     requires:
      #       - lint
      #       - danger
      # # - extension:
      # #     requires:
      # #       - lint
      # #       - danger
      # # Failure /usr/share/pgsql/extension/adminpack--1.0.sql: No such file or directory
      # - initdb:
      #     requires:
      #       - lint
      #       - danger

orbs:
  sous-chefs:
    executors:
      ruby:
        docker: [ image: circleci/ruby ]
      chef:
        machine: true
    jobs:
      danger:
        executor: ruby
        steps:
          - checkout
          - run:
              name: Install Danger
              command: gem install danger
          - run:
              name: Run Danger
              command: danger
      lint:
        executor: chef
        parameters:
          channel:
            description: ChefDK channel stable or current
            type: string
            default: current
        steps:
          - checkout
          - run:
              name: Install Chef
              command: curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -c <<parameters.channel>> -P chefdk
          - run:
              name: Unit Test
              command: chef exec delivery local all
